name: Lint using Flake8

on: [push]

env:
  PYTHON_VERSION: 3.8

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: x64
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8_py3'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}